import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="px-24">
        <header className='flex justify-between h-16 items-center mb-16'>
          <Link href={'/'}>
            <h1 className='text-3xl font-bold ' >
              logo
            </h1>
          </Link>
          <ul className='flex justify-between  w-64 gap-x-9'>
            <li> <Link href={'/'}>
              Home
            </Link>
            </li>
            <li> <Link href={'/products'}>
              Products
            </Link>
            </li>
            <li> <Link href={'/about'}>
              About
            </Link>
            </li>
            <li> <Link href={'/contact'}>
              Contact
            </Link>
            </li>
          </ul>
          <div className="flex gap-x-6">
            <button className='rounded px-3 py-1 border border-neutral-800'>Sign Up</button>
            <button
              className='rounded px-3 py-1 border border-neutral-800'>Login</button>
          </div>
        </header>
        {children}
      </body>

    </html>
  )
}

